// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMiAJp1QAthxxodRCGPv-7Jeie4aeVo4',
    appId: '1:146652436697:web:d17c298f696bdd03d306c8',
    messagingSenderId: '146652436697',
    projectId: 'skills-pathway-app',
    authDomain: 'skills-pathway-app.firebaseapp.com',
    storageBucket: 'skills-pathway-app.firebasestorage.app',
    measurementId: 'G-8VLL7YCFNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQ_kNEaQSevhJWVwkJ_718Ggei3GMBYM',
    appId: '1:146652436697:android:7c28bd5bddd042e2d306c8',
    messagingSenderId: '146652436697',
    projectId: 'skills-pathway-app',
    storageBucket: 'skills-pathway-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ukmVm4RTIEDAH6yAtTmw051QnzAHnV4',
    appId: '1:146652436697:ios:beb014ba1747a45fd306c8',
    messagingSenderId: '146652436697',
    projectId: 'skills-pathway-app',
    storageBucket: 'skills-pathway-app.firebasestorage.app',
    iosBundleId: 'com.skillspathway.app.skillsPathwayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ukmVm4RTIEDAH6yAtTmw051QnzAHnV4',
    appId: '1:146652436697:ios:beb014ba1747a45fd306c8',
    messagingSenderId: '146652436697',
    projectId: 'skills-pathway-app',
    storageBucket: 'skills-pathway-app.firebasestorage.app',
    iosBundleId: 'com.skillspathway.app.skillsPathwayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGMiAJp1QAthxxodRCGPv-7Jeie4aeVo4',
    appId: '1:146652436697:web:b63becd7063ec51ad306c8',
    messagingSenderId: '146652436697',
    projectId: 'skills-pathway-app',
    authDomain: 'skills-pathway-app.firebaseapp.com',
    storageBucket: 'skills-pathway-app.firebasestorage.app',
    measurementId: 'G-LSTD80HQTD',
  );
}
